drop table FIX_STRUCTURE_ELEMENT
drop table FIX_STRUCTURE
drop table FIX_FIELD
drop table FIX_FIELD_TYPE_SPEC
drop table FIX_FIELD_TYPE

create table FIX_FIELD_TYPE (
	TYPE_CD varchar(24) NOT NULL,
	PARENT_TYPE_CD varchar(24) NULL,
	CONSTRAINT PK__FIX_FIELD_TYPE PRIMARY KEY (TYPE_CD),
	CONSTRAINT FK__FIX_FIELD_TYPE__PARENT_TYPE_CD FOREIGN KEY (PARENT_TYPE_CD) REFERENCES FIX_FIELD_TYPE (TYPE_CD)
)

create table FIX_FIELD_TYPE_SPEC (
	TYPE_CD varchar(24) NOT NULL,
	FIX_VERSION varchar(12) NOT NULL,
	SCHEMA_CD varchar(16) NULL,
	FORMAT1 varchar(24) NOT NULL,
	FORMAT2 varchar(24) NOT NULL,
	MULTIPLIER float NOT NULL,
	CONSTRAINT UQ__FIX_FIELD_TYPE_SPEC UNIQUE (TYPE_CD, FIX_VERSION, SCHEMA_CD),
	CONSTRAINT FK__FIX_FIELD_TYPE_SPEC__TYPE_CD FOREIGN KEY (TYPE_CD) REFERENCES FIX_FIELD_TYPE (TYPE_CD) ON DELETE CASCADE
)

create table FIX_FIELD (
	FIELD_ID bigint NOT NULL,
	NAME varchar(48) NOT NULL,
	TAG_NUM int NOT NULL,
	TYPE_CD varchar(24) NOT NULL,
	CONSTRAINT PK__FIX_FIELD PRIMARY KEY (FIELD_ID),
	CONSTRAINT FK__FIX_FIELD__TYPE_CD FOREIGN KEY (TYPE_CD) REFERENCES FIX_FIELD_TYPE (TYPE_CD)
)

create table FIX_STRUCTURE (
	STRUCTURE_ID bigint NOT NULL,
	NAME varchar(48) NOT NULL,
	TYPE_CD char(1) NOT NULL,
	MSG_TYPE varchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NO_FIELD_ID bigint NULL,
	CONSTRAINT PK__FIX_STRUCTURE PRIMARY KEY (STRUCTURE_ID),
	CONSTRAINT UQ__FIX_STRUCTURE UNIQUE (NAME, TYPE_CD),
	CONSTRAINT FK__FIX_STRUCTURE__NO_FIELD_ID FOREIGN KEY (NO_FIELD_ID) REFERENCES FIX_FIELD (FIELD_ID),
	CONSTRAINT C__FIX_STRUCTURE CHECK (
		(TYPE_CD = 'M' AND MSG_TYPE IS NOT NULL AND NO_FIELD_ID IS NULL) OR
		(TYPE_CD = 'C' AND MSG_TYPE IS NULL AND NO_FIELD_ID IS NULL) OR
		(TYPE_CD = 'G' AND MSG_TYPE IS NULL AND NO_FIELD_ID IS NOT NULL))
)

create table FIX_STRUCTURE_ELEMENT (
	STRUCTURE_ID bigint NOT NULL,
	FIX_VERSION varchar(12) NOT NULL,
	SCHEMA_CD varchar(16) NULL,
	ORDER_NO int NOT NULL,
	SUB_STRUCTURE_ID bigint NULL,
	FIELD_ID bigint NULL,
	REQUIRED bit NOT NULL DEFAULT 0,
	TRAILING bit NOT NULL DEFAULT 0,
	CONSTRAINT UQ__FIX_STRUCTURE_ELEMENT UNIQUE (STRUCTURE_ID, FIX_VERSION, SCHEMA_CD, ORDER_NO),
	CONSTRAINT FK__FIX_STRUCTURE_ELEMENT__STRUCTURE_ID FOREIGN KEY (STRUCTURE_ID) REFERENCES FIX_STRUCTURE (STRUCTURE_ID) ON DELETE CASCADE,
	CONSTRAINT FK__FIX_STRUCTURE_ELEMENT__SUB_STRUCTURE_ID FOREIGN KEY (SUB_STRUCTURE_ID) REFERENCES FIX_STRUCTURE (STRUCTURE_ID),
	CONSTRAINT FK__FIX_STRUCTURE_ELEMENT__FIELD_ID FOREIGN KEY (FIELD_ID) REFERENCES FIX_FIELD (FIELD_ID),
	CONSTRAINT C__FIX_STRUCTURE_ELEMENT CHECK (
		(SUB_STRUCTURE_ID IS NOT NULL AND FIELD_ID IS NULL) OR
		(SUB_STRUCTURE_ID IS NULL AND FIELD_ID IS NOT NULL))
)