DROP TABLE FIX_CONNECTION
DROP TABLE FIX_ENGINE
DROP TABLE FIX_SERVER

CREATE TABLE FIX_SERVER (
	SERVER_ID BIGINT NOT NULL,
	CONSTRAINT PK__FIX_SERVER PRIMARY KEY (SERVER_ID)
)

CREATE TABLE FIX_ENGINE (
	ENGINE_ID BIGINT NOT NULL,
	SERVER_ID BIGINT NOT NULL,
	ACCEPTOR_HOST VARCHAR(32) NULL,
	ACCEPTOR_PORT INT NULL,
	CONSTRAINT PK__FIX_ENGINE PRIMARY KEY (ENGINE_ID),
	CONSTRAINT FK__FIX_ENGINE__SERVER_ID FOREIGN KEY (SERVER_ID) REFERENCES FIX_SERVER (SERVER_ID)
)

CREATE TABLE FIX_CONNECTION (
	CONNECTION_ID BIGINT NOT NULL,
	ENGINE_ID BIGINT NOT NULL,
	NAME VARCHAR(32) NOT NULL,
	ACCEPTOR BIT NOT NULL,
	FIX_VERSION VARCHAR(12) NOT NULL,
	TRANSPORT_VERSION VARCHAR(5) NULL,
	SENDER_COMP_ID VARCHAR(32) NOT NULL,
	SENDER_SUB_ID VARCHAR(32) NULL,
	SENDER_LOCATION_ID VARCHAR(32) NULL,
	TARGET_COMP_ID VARCHAR(32) NOT NULL,
	TARGET_SUB_ID VARCHAR(32) NULL,
	TARGET_LOCATION_ID VARCHAR(32) NULL,
	HOST VARCHAR(32) NULL,
	PORT INT NULL,
	FALLBACK_HOST1 VARCHAR(32) NULL,
	FALLBACK_PORT1 INT NULL,
	FALLBACK_HOST2 VARCHAR(32) NULL,
	FALLBACK_PORT2 INT NULL,
	HEARTBEAT_INTERVAL INT NULL,
	CONSTRAINT PK__FIX_CONNECTION PRIMARY KEY (CONNECTION_ID),
	CONSTRAINT UQ__FIX_CONNECTION__NAME UNIQUE (NAME),
	CONSTRAINT UQ__FIX_CONNECTION__SESSION_ID UNIQUE (SENDER_COMP_ID, SENDER_SUB_ID, SENDER_LOCATION_ID, TARGET_COMP_ID, TARGET_SUB_ID, TARGET_LOCATION_ID),
	CONSTRAINT FK__FIX_CONNECTION__ENGINE_ID FOREIGN KEY (ENGINE_ID) REFERENCES FIX_ENGINE (ENGINE_ID)
)