drop table DETERMINANT_CRITERION_VALUE
drop table DETERMINANT_CRITERION
drop table DETERMINANT_CRITERION_UNION
drop table DETERMINANT
drop table DETERMINANT_PROPERTY
drop table DETERMINANT_TYPE

create table DETERMINANT_TYPE (
	TYPE_CD varchar(10) NOT NULL,
	DESCRIPTION varchar(128) NOT NULL,
	CONSTRAINT PK__DETERMINANT_TYPE PRIMARY KEY (TYPE_CD)
)

create table DETERMINANT_PROPERTY (
	PROP_ID bigint NOT NULL,
	TYPE_CD varchar(10) NOT NULL,
	NAME varchar(256) NOT NULL,
	CONSTRAINT PK__DETERMINANT_PROPERTY PRIMARY KEY (PROP_ID)
)

create table DETERMINANT (
	DETERM_ID bigint NOT NULL,
	TYPE_CD varchar(10) NOT NULL,
	NAME varchar(32) NOT NULL,
	DESCRIPTION varchar(64) NOT NULL,
	PARENT_ID bigint NULL,
	PRIORITY float NOT NULL,
	ACTIVE bit NOT NULL DEFAULT 1,
	CONSTRAINT PK__DETERMINANT PRIMARY KEY (DETERM_ID),
	CONSTRAINT FK__DETERMINANT__TYPE_CD FOREIGN KEY (TYPE_CD) REFERENCES DETERMINANT_TYPE (TYPE_CD),
	CONSTRAINT FK__DETERMINANT__PARENT_ID FOREIGN KEY (PARENT_ID) REFERENCES DETERMINANT (DETERM_ID)
)

create table DETERMINANT_CRITERION_UNION (
	DETERM_ID bigint NOT NULL,
	ORDER_NO int NOT NULL,
	PARENT_ORDER_NO int NULL,
	NEGATE bit NOT NULL DEFAULT 0,
	SHORT_CIRCUIT bit NOT NULL DEFAULT 0,
	CONSTRAINT PK__DETERMINANT_CRITERION_UNION PRIMARY KEY (DETERM_ID, ORDER_NO),
	CONSTRAINT FK__DETERMINANT_CRITERION_UNION__DETERM_ID FOREIGN KEY (DETERM_ID) REFERENCES DETERMINANT (DETERM_ID),
	CONSTRAINT FK__DETERMINANT_CRITERION_UNION__PARENT_ORDER_NO FOREIGN KEY (DETERM_ID, PARENT_ORDER_NO) REFERENCES DETERMINANT_CRITERION_UNION (DETERM_ID, ORDER_NO)
)

create table DETERMINANT_CRITERION (
	DETERM_ID bigint NOT NULL,
	ORDER_NO int NOT NULL,
	UNION_ORDER_NO int NULL,
	PROP_ID bigint NOT NULL,
	NEGATE bit NOT NULL DEFAULT 0,
	OPERATOR_CD varchar(5) NOT NULL,
	VALUE_TYPE_CD varchar(10) NOT NULL,
	SHORT_CIRCUIT bit NOT NULL DEFAULT 0,
	CONSTRAINT PK__DETERMINANT_CRITERION PRIMARY KEY (DETERM_ID, ORDER_NO),
	CONSTRAINT FK__DETERMINANT_CRITERION__DETERM_ID FOREIGN KEY (DETERM_ID) REFERENCES DETERMINANT (DETERM_ID),
	CONSTRAINT FK__DETERMINANT_CRITERION__UNION_ORDER_NO FOREIGN KEY (DETERM_ID, UNION_ORDER_NO) REFERENCES DETERMINANT_CRITERION_UNION (DETERM_ID, ORDER_NO),
	CONSTRAINT FK__DETERMINANT_CRITERION__PROP_ID FOREIGN KEY (PROP_ID) REFERENCES DETERMINANT_PROPERTY (PROP_ID)
)

create table DETERMINANT_CRITERION_VALUE (
	DETERM_ID bigint NOT NULL,
	ORDER_NO int NOT NULL,
	VALUE varchar(128) NOT NULL,
	SUPP_VALUE1 varchar(128) NULL,
	SUPP_VALUE2 varchar(128) NULL,
	CONSTRAINT UQ__DETERMINANT_CRITERION_VALUE UNIQUE (DETERM_ID, ORDER_NO, VALUE),
	CONSTRAINT FK__DETERMINANT_CRITERION_VALUE__ORDER_NO FOREIGN KEY (DETERM_ID, ORDER_NO) REFERENCES DETERMINANT_CRITERION (DETERM_ID, ORDER_NO)
)